version: '2'
services:
  mongo:
    image: mongo:3.4
  node_modules:
    build:
     context: .
     dockerfile: Dockerfile_nodemodules
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
     - MONGOLAB_URI=mongodb://dbuser:1233211@ds141410.mlab.com:41410/getir-hackathon
    links:
     - mongo
    depends_on:
     - mongo
    volumes:
     - .:/wow
     - /wow/node_modules
